### ISSUE TITLE
Update to use Obvs 5.0 and .NET Standard 2.0

### ISSUE THREAD

**Issue by cyberop5** [christopherread/Obvs.NetMQ#6]

**Comment by danielz1985** [comment]
Any feedback on the open pull request?

**Comment by cyberop5** [comment]
Doesn't add support for .NET Standard 2.0. Obvs5 does support it.

**Comment by christopherread** [comment]
Hi sorry for the delay, I have commented on the PR now.

Has anyone had a chance to test the code in the PR to verify it?

**Comment by christopherread** [comment]
This has been done, and deployed as Obvs.NetMQ.5.0.0.2 to nuget.org. Thanks!
